### ISSUE TITLE
segfault when passing an IOStream to JLD2.load

### ISSUE THREAD

**Issue by sbromberger** [simonster/JLD2.jl#19]
After
```
a = sprand(100, 100, 0.5)
@save "testjld2" a
```

I tried to pass an IOStream to `load`:
```
f = open("testjld2", "r")
# IOStream(<file testjld2>)

JLD2.load(f)
Segmentation fault: 11
```

~It'd be great if JLD2.load could take an IOStream.~ The docs imply that it should work.

**Comment by simonster** [comment]
The segfault is caused by a stack overflow in FileIO:

```
 [2] #load#20(::Array{Any,1}, ::Function, ::FileIO.Stream{FileIO.DataFormat{:JLD2},IOStream}) at /Users/simon/.julia/v0.6/FileIO/src/loadsave.jl:103
 [3] load(::FileIO.Stream{FileIO.DataFormat{:JLD2},IOStream}) at /Users/simon/.julia/v0.6/FileIO/src/loadsave.jl:86
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] #load#20(::Array{Any,1}, ::Function, ::FileIO.Stream{FileIO.DataFormat{:JLD2},IOStream}) at /Users/simon/.julia/v0.6/FileIO/src/loadsave.jl:98
 [6] load(::FileIO.Stream{FileIO.DataFormat{:JLD2},IOStream}) at /Users/simon/.julia/v0.6/FileIO/src/loadsave.jl:86
 [7] eval(::Module, ::Any) at ./boot.jl:235
```

JLD2 does not implement `load` for IOStreams (and I don't think the docs imply it does). Additionally, Julia appears to crash when the stack overflows because there isn't enough stack left to print the error. I think the appropriate fix here is to change FileIO so that the `load` fallback does not call itself when it fails.

Making JLD2 take an IOStream is likely more effort than it's worth. You'd either have to find a way to go from the IOStream back to the file path, or tolerate data corruption if an IOStream corresponding to a JLDFile opened for writing is closed prematurely (either by the user or because the finalizer for it runs before the finalizer for the JLDFile) or if the file is opened multiple times.

**Comment by sbromberger** [comment]
Here's the part of the docstring that confused me:

```
help?> JLD2.load
    •    load(filename) loads the contents of a formatted file, trying to infer


  the format from filename and/or magic bytes in the file.

    •    load(strm) loads from an IOStream or similar object. In this case,


  the magic bytes are essential.

    •    load(File(format"PNG",filename)) specifies the format directly, and bypasses inference.

    •    load(f; options...) passes keyword arguments on to the loader.
```

**Comment by simonster** [comment]
That doc string also comes from FileIO:

```
julia> FileIO.load == JLD2.load
true
```

It could be amended to note that loading from an IO will only work for formats that can be loaded from IOs, but I'm not sure this would be necessary if it actually threw an error instead of causing a stack overflow.

**Comment by timholy** [comment]
Are you extending `FileIO.load`? You shouldn't, it should not be an exported name. JLD was written before FileIO existed so it exported `load`, but since this package is new you have a chance to make breaking changes.

**Comment by timholy** [comment]
See #20
